htmlAPIClientStoreHouse/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;

namespace htmlAPIClientStoreHouse.Controllers
{
    public class CustomerController : Controller
    {

        public ActionResult GetAll()
        {
            return View("ListOfCustomers");
        }

        public ActionResult AddCustomerFields()
        {
            return View();
        }
        
        public ActionResult EditCustomerFields(int id)
        {
            ViewData["CustomerId"] = id;
            return View();
        }

        public ActionResult GetCustomerOrders(int id)
        {
            return Redirect("/Order/GetAll/"+id);
        }
    }
}

htmlAPIClientStoreHouse/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace htmlAPIClientStoreHouse.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;


        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Customer()
        {
            return View();
        }

        public IActionResult Product()
        {
            return View();
        }

    }
}

htmlAPIClientStoreHouse/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace htmlAPIClientStoreHouse.Controllers
{
    public class OrderController : Controller
    {
        public ActionResult GetAll(int id)
        {
            ViewData["CustomerId"] = id;
            return View("GetCustomerOrders");
        }
        
        public ActionResult AddProductToOrder(int id,int cusId)
        {
            
            ViewData["OrderId"] = id;
            ViewData["CustomerId"] = cusId;
            return View("AddProductToOrder");
        }
    }
}

htmlAPIClientStoreHouse/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace htmlAPIClientStoreHouse.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult GetAll()
        {
            return View("ListOfProducts");
        }

        public ActionResult FindProductByName()
        {
            return View("FindProductByName");
        }
        public ActionResult EditProductFields(int id)
        {
            ViewData["ProductId"] = id;
            return View("EditProductFields");
        }
        

        public ActionResult AddProduct()
        {
            return View("AddProductFields");
        }
    }
}

htmlAPIClientStoreHouse/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace htmlAPIClientStoreHouse.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

htmlAPIClientStoreHouse/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace htmlAPIClientStoreHouse.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

htmlAPIClientStoreHouse/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace htmlAPIClientStoreHouse.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

htmlAPIClientStoreHouse/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

htmlAPIClientStoreHouse/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - htmlAPIClientStoreHouse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">htmlAPIClientStoreHouse</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - htmlAPIClientStoreHouse - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

htmlAPIClientStoreHouse/Views/Customer/AddCustomerFields.cshtml
<h1>AddCustomer</h1>

<table>
    <form method="post" action="">
        <p>
            <label>Name:</label><br />
            <input type="text" id="customerName" name="CustomerName" />
        </p>
        <p>
            <label>Email:</label><br />
            <input type="Email" id="customerEmail" name="CustomerEmail" />
        </p>
        <p>
            <input type="button" value="Отправить" onclick="addCustomer()" />
        </p>
    </form>
</table>


<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'https://localhost:5001/Store';

    function addCustomer() {
        var customer = {
            customerName: $('#customerName').val(),
            customerEmail: $('#customerEmail').val()
        };
        var dataJson = JSON.stringify(customer);

        var URL = uri + '/Customer/Add';
        $.ajax({
            type: "POST",
            url: URL,
            data: dataJson,
            dataType: "json",
            contentType: 'application/json; charset=utf-8'
        });
    }
</script>

htmlAPIClientStoreHouse/Views/Customer/EditCustomerFields.cshtml
<h1>EditCustomer</h1>

<table>
    <form method="post" action="">
        <p>
            <label>Name:</label><br />
            <input type="text" id="customerName" name="CustomerName" />
        </p>
        <p>
            <label>Email:</label><br />
            <input type="Email" id="customerEmail" name="CustomerEmail" />
        </p>
        <p>
            <input type="button" value="Отправить" onclick="updateCustomer()" />
        </p>
    </form>
</table>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'https://localhost:5001/Store';

    function updateCustomer() {
        var customer = {
            customerId: @ViewData["CustomerId"],
            customerName: $('#customerName').val(),
            customerEmail: $('#customerEmail').val()
        };
        var dataJson = JSON.stringify(customer);

        var URL = uri + '/Customer/Update';
        $.ajax({
            type: "PUT",
            url: URL,
            data: dataJson,
            dataType: "json",
            contentType: 'application/json; charset=utf-8'
        });
        window.location.href = "/Customer/GetAll";
    }
</script>

htmlAPIClientStoreHouse/Views/Customer/ListOfCustomers.cshtml
<h1>Customer</h1>

<table id="customers" class="table-hover table">
    <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Email</td>
        <td>functions</td>
    </tr>

</table>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'https://localhost:5001/Store';

    $(document).ready(getAllCustomers);

    function getAllCustomers() {
        $.getJSON(uri + '/Customer/GetAll')
            .done(function (data) {
                $("#customers").find("tr:gt(0)").remove();
                $.each(data,
                    function (key, item) {
                        $('<tr>').append(formatItem(item)).appendTo($('#customers'));
                    }
                );
            }
        );
    }

    function formatItem(item) {
        return [
            $('<td>', { text: item.customerId }), $('<td>', { text: item.customerName }), $('<td>', { text: item.customerEmail }),
            $('<td>').append([$('<a>', { class: "mr-1 btn btn-outline-primary", text: "Delete", onclick: "deleteCustomer(" + item.customerId + ")" }), $('<a>', { class: "mr-1 btn btn-outline-primary", text: "Edit", href: "/Customer/EditCustomerFields/" + item.customerId }), $('<a>', { class: "mr-1 btn btn-outline-primary", text: "Orders", href: "/Customer/GetCustomerOrders/" + item.customerId })])
        ];
    }

    function deleteCustomer(id) {
        var URL = uri + '/Customer/Delete/' + id;
        console.log(URL);
        $.ajax({
            url: URL,
            type: 'DELETE',
            success: function (result) {
                getAllCustomers();
            }
        });
    }
</script>

htmlAPIClientStoreHouse/Views/Home/Customer.cshtml
<h1>Customer</h1>

<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="GetAll">Get all customers</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="AddCustomerFields">Add customer</a>
    </li>
</ul>

htmlAPIClientStoreHouse/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">OrderHouse </h1>
</div>

htmlAPIClientStoreHouse/Views/Home/Product.cshtml
@{
    ViewData["Product"] = "Product";
}
<h1>@ViewData["Product"]</h1>

<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="GetAll">Get all products</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="FindProductByName">Get product by name</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="AddProduct">Add product</a>
    </li>
</ul>

htmlAPIClientStoreHouse/Views/Order/AddProductToOrder.cshtml
<h1>Add Product</h1>

<table>
    <form method="post" action="">
        <p>
            <label>Name:</label><br />
            <input type="text" id="productName" name="ProductName" />
        </p>
        <p>
            <input type="button" value="Отправить" onclick="addProduct()" />
        </p>
    </form>
</table>


<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'https://localhost:5001/Store';


    function addProduct() {
        $.getJSON(uri + '/Product/Get/' + $('#productName').val())
            .done(function (data) {
                var URL = uri + '/Order/AddProduct/' + @ViewData["OrderId"] + '/' + data.productId;
                $.ajax({
                    type: "PUT",
                    url: URL
                });
                location.replace("/Order/GetAll/"+@ViewData["CustomerId"]);
            })
    }
</script>

htmlAPIClientStoreHouse/Views/Order/GetCustomerOrders.cshtml
@{
    ViewData["Order"] = "Orders";
}
<h1>@ViewData["Order"]</h1>

ViewData["CustomerId"] = id;


<style>
    td {
        text-align: center;
        vertical-align: middle;
    }
</style>

<table id="mainTable" class="table table-bordered">
    <tr>
        <td>orderId</td>
        <td>Products In Order</td>
    </tr>
    <tr></tr>
</table>
<tr>
    <td>
    <tr>
        <td>
            <a class= "mr-1 btn btn-outline-primary" onclick="addProductToOrder()">Create Order</a>
        </td>
    </tr>
</tr>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'https://localhost:5001/Store';
    $(document).ready(getAllOrders);

    function getAllOrders() {
        $.getJSON(uri + '/Order/Get/'+@ViewData["CustomerId"])
            .done(function (data) {
                $("#mainTable").find("tr:gt(0)").remove();
                $.each(data,
                    function (key, item) {
                        $('<tr>').append(formatItem(item)).appendTo($('#mainTable'));
                    });
            });
    }

    function formatItem(item) {
        var row = $("<td>");
        $('<tr>').append([$('<td>', { text: "productId" }),
            $('<td>', { text: "productName" }),
            $('<td>', { text: "productPrice" }),
            $('<td>', { text: "count" })
        ]).appendTo(row);
        $.each(item.orderProducts,
            function (key, data) {
                row.append(($('<tr>').append([$('<td>', { text: data.productId }),
                    $('<td>', { text: data.productName }),
                    $('<td>', { text: data.productPrice }),
                    $('<td>', { text: data.count }),
                    $('<td>').append($('<a>', { class: "mr-1 btn btn-outline-primary", text: "Delete", onclick: "deleteProductFromOrder(" + item.orderId + ',' + data.productId+ ")" }))
                ])));
            });

        return [
            $('<td>', { text: item.orderId }), row, $('<td>').append([$('<tr>').append($('<td>').append($('<a>', { class: "mr-1 btn btn-outline-primary", text: "Delete", onclick: "deleteOrder(" + item.orderId + ")" }))), $('<tr>').append($('<td>').append($('<a>', { class: "mr-1 btn btn-outline-primary", text: "Add Product", href: "/Order/AddProductToOrder" + '?id=' + item.orderId +'&cusId='+@ViewData["CustomerId"] })))])
        ];
    }

    function addProductToOrder() {
        var order = {
            customerId: @ViewData["CustomerId"]
        };
        var dataJson = JSON.stringify(order);

        var URL = uri + '/Order/Create';
        $.ajax({
            type: "POST",
            url: URL,
            data: dataJson,
            dataType: "json",
            contentType: 'application/json; charset=utf-8'
        });
        getAllOrders();
    }

    function deleteOrder(id) {
        var URL = uri + '/Order/Delete/'+id
        $.ajax({
            type: "DELETE",
            url: URL
        });
        location.reload();
    }

    function deleteProductFromOrder(orderId,productId)
    {
        var URL = uri + '/Order/RemoveProduct/' + orderId + '/' + productId;
        $.ajax({
            type: "PUT",
            url: URL
        });
        location.reload();
    }


</script>

htmlAPIClientStoreHouse/Views/Order/NullOrdersException.cshtml
<h1>@ViewData["ExceptionMessage"]</h1>

<a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a>
<a asp-action="CreateOrder" asp-controller="Order" asp-route-customerId="@ViewBag.OrderCustomerId">Create Order</a>

htmlAPIClientStoreHouse/Views/Product/AddProductFields.cshtml
@using htmlAPIClientStoreHouse.Controllers
@{
    ViewData["Title"] = "Add Product";
}
<h1>@ViewData["Title"]</h1>

<table>
    <form method="post" action="">
        <p>
            <label>Name:</label><br />
            <input type="text" id="productName" name="ProductName" />
        </p>
        <p>
            <label>Price:</label><br />
            <input type="number" id="productPrice" name="ProductPrice" />
        </p>
        <p>
            <label>Count:</label><br />
            <input type="number" id="count" name="Count" />
        </p>
        <p>
            <input type="button" value="Отправить" onclick="addProduct()" />
        </p>
    </form>
    <p id="textHolder"></p>
</table>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'https://localhost:5001/Store';

    function addProduct() {
        var product = {
            productName: $('#productName').val(),
            productPrice: parseInt($('#productPrice').val()),
            count: parseInt($('#count').val())
        };
        var dataJson = JSON.stringify(product);

        var URL = uri + '/Product/Add';
        $.ajax({
            type: "POST",
            url: URL,
            data: dataJson,
            dataType: "json",
            contentType: 'application/json; charset=utf-8'
        });
    }
</script>

htmlAPIClientStoreHouse/Views/Product/EditProductFields.cshtml
@using htmlAPIClientStoreHouse.Controllers
@{
    ViewData["Title"] = "Edit Product";
}
<h1>@ViewData["Title"]</h1>

<table>
    <form method="post" action="">
        <p>
            <label>Name:</label><br />
            <input type="text" id="productName" name="ProductName" />
        </p>
        <p>
            <label>Price:</label><br />
            <input type="number" id="productPrice" name="ProductPrice" />
        </p>
        <p>
            <label>Count:</label><br />
            <input type="number" id="count" name="Count" />
        </p>
        <p>
            <input type="button" value="Отправить" onclick="editProduct()" />
        </p>
    </form>
</table>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'https://localhost:5001/Store';

    function editProduct() {
        var product = {
            productId: parseInt(@ViewData["ProductId"]),
            productName: $('#productName').val(),
            productPrice: parseInt($('#productPrice').val()),
            count: parseInt($('#count').val())
        };
        var dataJson = JSON.stringify(product);

        var URL = uri + '/Product/Edit';
        $.ajax({
            type: "PUT",
            url: URL,
            data: dataJson,
            dataType: "json",
            contentType: 'application/json; charset=utf-8'
        });
        window.location.href = "/Product/GetAll";
    }
</script>

htmlAPIClientStoreHouse/Views/Product/FindProductByName.cshtml
@using htmlAPIClientStoreHouse.Controllers
@{
    ViewData["Title"] = "Find Product";
}
<h1>@ViewData["Title"]</h1>

<table>
    <form method="post" action="">
        <p>
            <label>Name:</label><br />
            <input type="text" id="productName" name="ProductName" />
        </p>
        <p>
            <input type="button" value="Отправить" onclick="find()" />
        </p>
    </form>

    <table id="products" class="table table-hover">
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Price</td>
            <td>Count</td>
        </tr>
        <tr>
            
        </tr>
    </table>
</table>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'https://localhost:5001/Store';

    function formatItem(item) {
        return [$('<td>', { text: item.productId }), $('<td>', { text: item.productName }), $('<td>', { text: item.productPrice }), $('<td>', { text: item.count })];
    }

    function find() {
        $.getJSON(uri + '/Product/Get/' + $('#productName').val())
            .done(function (data) {
                $('#products tr:last').remove();
                $('#products').append($('<tr>').append(formatItem(data)));
            })
            .fail(function(jqXHR, textStatus, err) {
                //$('#products').text('Error: ' + err);
                $('#products tr:last').remove();
                $('#products').append($('<tr>', { text: 'Error: ' + err.responseText}));
            });
    }
</script>

htmlAPIClientStoreHouse/Views/Product/ListOfProducts.cshtml
@using htmlAPIClientStoreHouse.Controllers
@{
    ViewData["Product"] = "Product";
}
<h1>@ViewData["Product"]</h1>

<table id="products" class="table table-hover">
    <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Price</td>
        <td>Count</td>
        <td>functions</td>
    </tr>
    <tr></tr>
</table>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'https://localhost:5001/Store';

    $(document).ready(getAllProducts);

    function getAllProducts() {
        $.getJSON(uri + '/Product/GetAll')
            .done(function (data) {
                $("#products").find("tr:gt(0)").remove();
                $.each(data,
                    function (key, item) {
                        $('<tr>').append(formatItem(item)).appendTo($('#products'));
                    });
            });
    }

    function formatItem(item) {
        return [
            $('<td>', { text: item.productId }),
            $('<td>', { text: item.productName }),
            $('<td>', { text: item.productPrice }),
            $('<td>', { text: item.count }),
            $('<td>').append([$('<a>', { class: "mr-1 btn btn-outline-primary", text: "Delete", onclick: "deleteProduct(" + item.productId + ")" }), $('<a>', { class: "mr-1 btn btn-outline-primary", text: "Edit", href: "/Product/EditProductFields/" + item.productId })])
        ];
    }

    function redirectToChange(id) {
        window.location.href = "/Product/EditProductFields";
    }

    function deleteProduct(id) {
        var URL = uri + '/Product/Delete/' + id;
        $.ajax({
            url: URL,
            type: 'DELETE',
            success: function (result) {
                getAllProducts();
            }
        });
    }
</script>

htmlAPIClientStoreHouse/Views/Shared/ExceptionMessage.cshtml
<h1>@ViewData["ExceptionMessage"]</h1>

<a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a>

htmlAPIClientStoreHouse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PLMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Product">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Customer">Customers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PLMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>